# Generated by Django 5.2.9 on 2025-12-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcontentblock',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='blogcontentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/content/'),
        ),
        migrations.AlterField(
            model_name='blogcontentblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
